# SPDX-FileCopyrightText: 2025 The paliwa development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: CC-BY-4.0

name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  build:
    name: build-and-test (MPI: ${{ matrix.mpi }}, ${{ matrix.build_type }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi:         [yes, no]
        build_type:  [Release, Debug]
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    # cf. https://github.com/spack/setup-spack
    - name: Set up Spack
      uses: spack/setup-spack@5ab3c91bdefffffad9a7e45d1d156146afebb3a7
      with:
        ref: develop      # Spack version (examples: develop, releases/v0.23)
        buildcache: true  # Configure oci://ghcr.io/spack/github-actions-buildcache
        color: true       # Force color output (SPACK_COLOR=always)
        path: spack       # Where to clone Spack
    - name: Install system dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc python3
    - name: Set up ddc-env
      shell: spack-bash {0}
      run: |
        spack compiler find
        spack external find
        spack config add "packages:cmake:buildable:false"
        spack config add "packages:python:buildable:false"
        spack env create ddc-env
        spack --env ddc-env add ddc@main -splines -fft #...+cuda cuda_arch=...
        spack --env ddc-env add googletest
        if [ "${{ matrix.mpi }}" == "yes" ]; then
          spack --env ddc-env add mpi
        fi
        spack --env ddc-env add py-pip
        spack --env ddc-env install
        spack env activate ddc-env
        spack env status
    - name: Build with CMake
      shell: spack-bash {0}
      run: |
        spack env activate ddc-env
        mkdir build
        ls -l
        if [ "${{ matrix.mpi }}" == "yes" ]; then
          cmake -DPALIWA_BUILD_TESTS=ON -DPALIWA_WITH_MPI=ON -B build
        else
          cmake -DPALIWA_BUILD_TESTS=ON -DPALIWA_WITH_MPI=OFF -B build
        fi
        cmake --build ./build/ --config ${{ matrix.build_type }}
    - name: Run tests
      shell: spack-bash {0}
      run: |
        spack env activate ddc-env
        cd build
        ./test/paliwa_tests        
